server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
  application:
    name: user-service
mybatis:
  type-aliases-package: com.example.beans
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka

